apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: sqream-demo.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: demo
          servicePort: 80
