repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx/
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com/

releases:
    - name: demo
      namespace: demo
      chart: ./demo
      version: 1.0.0

    - name: prometheus
      namespace: demo
      chart: stable/prometheus
      installed: true
      set:
        - name: server.ingress.enabled
          value: true
        - name: server.ingress.hosts[0]
          value: argus-demo.cloud
        - name: server.ingress.annotations.kubernetes\.io/ingress\.class
          value: nginx
        - name: server.service.type
          value: ClusterIP

    - name: ingress
      namespace: demo
      chart: ingress-nginx/ingress-nginx
      installed: true

